Excel unloading
skyvlados/TIAE-finance pull request #21
Opened 2022-07-21 20:26 UTC by skyvlados

2022-07-22 13:39 UTC, eugeneyak requested changes

2022-07-22 13:39 UTC, eugeneyak commented on app/views/operations/index.xlsx.axlsx
> +  style1 = wb.styles.add_style(bg_color: '006633', fg_color: 'FFFFFF')
какое-то сомнительное название переменной тут

2022-07-23 17:02 UTC, skyvlados commented on app/views/operations/index.xlsx.axlsx
> +  style1 = wb.styles.add_style(bg_color: '006633', fg_color: 'FFFFFF')
поправил

2022-07-25 14:17 UTC, eugeneyak approved these changes

2022-07-25 17:42 UTC, merged