First iteration registration
skyvlados/TIAE-finance pull request #26
Opened 2022-08-04 20:55 UTC by skyvlados

2022-08-07 15:47 UTC, eugeneyak requested changes

2022-08-07 15:47 UTC, eugeneyak commented on app/controllers/users_controller.rb
> +    @user.destroy
скорее всего, это не поможет, так как будут зависимые сущности, нужно: либо проверять, удалилось ли
либо удалять каскадно
либо вообще не делать удаление
делать удаление ненастоящее, просто помечая удаленным

2022-08-07 15:47 UTC, eugeneyak commented on app/controllers/users_controller.rb
> +      flash[:notice] = "User '#{old_name}' successfully updated to '#{@user.name}'!"
а если он не имя меняет, а что-то другое, например, пароль?

2022-08-07 15:47 UTC, eugeneyak commented on app/helpers/users_helper.rb
> +# frozen_string_literal: true
кажется, такой хелпер уже есть, можно вынести его в более общее место и переиспользовать

2022-08-07 15:47 UTC, eugeneyak commented on app/services/user_query.rb
> +    scope.where('email LIKE ?', "%#{params[:email]}%")
раз уж хранишь в базе емейлы в нижнем регистре, то и тут надо приводить в нижний или использовать ILIKE

2022-08-07 15:47 UTC, eugeneyak commented on db/migrate/20220804080913_create_users.rb
> +      t.string :email, null: false
в первую очередь, уникальность емейлов должна гарантировать именно база данных

2022-08-07 15:47 UTC, eugeneyak commented on app/controllers/users_controller.rb
> +class UsersController < ApplicationController
выглядит как типичный круд контроллер, что подразумевает, будто именно ты управляешь пользователями и не подразумевает классическую регистрацию

2022-08-07 15:47 UTC, eugeneyak commented on tableIncomAndExpeditureWithERB_development
> +ls
а ето шо?)

2022-08-07 18:37 UTC, skyvlados commented on app/controllers/users_controller.rb
> +class UsersController < ApplicationController
А как тогда должен называться контроллер классической регистрации, кажется что в материале https://www.softcover.io/read/db8803f7/ruby_on_rails_tutorial_3rd_edition_russian/sign_up, который ты мне скинул, контроллер юзеров также как и у меня называется?

2022-08-08 15:06 UTC, eugeneyak requested changes

2022-08-08 15:06 UTC, eugeneyak commented on app/models/user.rb
> +class User < ApplicationRecord
нужно добавить либо дефолт скоуп, либо просто скоуп неудаленных пользователей, раз уж ты сделал фиктивное удаление, и, если это обычный скоп, вызывать его в листе пользователей, поиске профиля и тд

https://apidock.com/rails/ActiveRecord/Base/default_scope/class

2022-08-08 15:06 UTC, eugeneyak commented on app/controllers/users_controller.rb
> +    @user = User.find(params[:id])
кста, вот это дейсвие делается примерно везде, его можно вынести отдельно в бефор экшн, что-то типа

```rb
before_action :find_user

def find_user
  @user = User.find(params[:id])
end
```

https://guides.rubyonrails.org/action_controller_overview.html#filters

2022-08-09 09:06 UTC, eugeneyak commented on app/controllers/categories_controller.rb
> +  skip_before_action :find_category, only: %i[index new create]
чего так сложно?)
можно же `before_action :find_category, only: %i[show update delete]`
или `before_action :find_category, except: %i[index new create]`

2022-08-09 12:03 UTC, eugeneyak approved these changes

2022-08-09 12:10 UTC, merged