admin panel only for admin
skyvlados/TIAE-finance pull request #32
Opened 2022-08-26 09:09 UTC by skyvlados

2022-08-26 09:18 UTC, eugeneyak requested changes

2022-08-26 09:18 UTC, eugeneyak commented on app/controllers/users_controller.rb
> +      @pagy, @users = pagy(scope.order(id: :desc).where(is_deleted: false), items: params[:page_size])
так а почему у тебя тут опять запрос конструируется? ты же специально делаешь UserQuery, чтобы в неи инкапсулировать его

2022-08-26 09:18 UTC, eugeneyak commented on app/controllers/users_controller.rb
>    skip_before_action :check_session, only: %i[new create]
ну и кстати, я чото не понял, зачем пропускать проверку возйденности?

2022-08-26 09:18 UTC, eugeneyak commented on app/controllers/users_controller.rb
> +    if current_user.is_admin
весьма очевидно, что если какая-то проверка делается в каждом экшене, то ее надо вынести в бефоре экшен

2022-08-26 09:18 UTC, eugeneyak commented on test/fixtures/users.yml
>  test2:
кажется, что довольно логично назвать этого пользователя не test2, а, например, admin, и это, потом, при вызове в тестах будет понятно куда более явно, когда будет log_in_as(users(:admin))

2022-08-26 11:09 UTC, skyvlados commented on app/controllers/users_controller.rb
>    skip_before_action :check_session, only: %i[new create]
так если не пропускать check_session для new и create, тогда будет не создать нового юзера

2022-08-27 14:59 UTC, eugeneyak commented on app/controllers/users_controller.rb
> +  before_action :user_is_admin, only: %i[index show edit update destroy]
а зачем убирать предыдущий before_action который теперь опять дублируется во всех экшенах?

их же можно комбинировать

before_action :user_is_admin, only: %i[index show edit update destroy]
before_action :find_user, only: %i[show edit update destroy]

skip_before_action :check_session, only: %i[new create]

и тд

2022-08-27 14:59 UTC, eugeneyak commented on app/controllers/users_controller.rb
>    skip_before_action :check_session, only: %i[new create]
чегой чегой?) 
пропуск check_session позволяет войти на страницуф любобу неаторизованному лицу, заполнить форму, отправить ее, и лишь после этого получить сообщение, что вообще-то надо войти

а по логике надо все-таки сразу говорить, что тебе надо сначала войти, а потом уже позволять заполнять формы

2022-08-30 14:30 UTC, eugeneyak approved these changes

2022-08-30 15:08 UTC, merged