Forgot password
skyvlados/TIAE-finance pull request #34
Opened 2022-10-18 14:21 UTC by skyvlados

2022-10-19 14:47 UTC, eugeneyak requested changes

2022-10-19 14:47 UTC, eugeneyak commented on app/helpers/button_helper.rb
> +    when 'forgot_password' then 'Sent instruction to email'
я бы сделал для этого отдельный хелпер, все-таки это немного другие задачи решает

2022-10-19 14:47 UTC, eugeneyak commented on app/views/user_mailer/password_recovery.html.erb
> +Hi
было бы прикольно, канеш, все-таки тут еще имя подписывать, а то как-то дерзко получается

2022-10-19 14:47 UTC, eugeneyak commented on config/routes.rb
> +  get '/forgot_password', to: 'password_recovery#forgot_password', as: 'forgot_password'
в целом, мне кажется, тут было бы хорошей идеей поиграться с путями и сложить их в дополнительный уровень вложенности, чтобы было что-то типа такого:
```
/password/forgot
/password/recovery
/password/confirm_recovery
/password/new
```

2022-10-19 15:14 UTC, eugeneyak commented on config/routes.rb
> +  get '/forgot_password', to: 'password_recovery#forgot_password', as: 'forgot_password'
https://guides.rubyonrails.org/routing.html#controller-namespaces-and-routing

2022-10-21 14:17 UTC, eugeneyak commented on app/controllers/application_controller.rb
> +  before_action :check_session,
а зачем ставить в пайплайн check_session, но пропускать ее полностью для всех экшенов?

2022-10-21 14:18 UTC, eugeneyak commented on app/controllers/password_recovery_controller.rb
> +    render :forgot_password
в принципе, это не обязательно писать, если все лежит в нужных папочках, рельсы итак автоматически найдут нужную вьюху и отреднерят ее, можно оставить пустой метод

2022-10-22 15:18 UTC, skyvlados commented on app/controllers/application_controller.rb
> +  before_action :check_session,
так я и не для всех экшенов пропускаю check_session, а только для тех, для которых проверка сессии не требуется

2022-10-22 15:26 UTC, skyvlados commented on app/controllers/password_recovery_controller.rb
> +    render :forgot_password
Поправил и в других местах, помню это правило, просто иногда очень хочется написать что рендерить, несмотря на логичность)

2022-10-22 17:48 UTC, eugeneyak commented on app/controllers/password_recovery_controller.rb
> +    render :forgot_password
ну если нравится, можешь писать, я просто отметил, а то мало ли, не знаешь

2022-10-22 17:52 UTC, eugeneyak commented on app/controllers/application_controller.rb
> +  before_action :check_session,
а я понял проблему, ты тут правила солида нарушаешь, ApplicationController это родительский котроллер, от которого наследуются дочерние, и родительский класс вообще никак не должен знать о детях, а у тебя имеено в нем указывается это

Как только у тебя появится любой другой дочерний класс с таким же экшеном, у тебя будет проблема, и ты не сразу и найдешь ее при этом

В твоем случае, именно в дочернем и надо пропускать проверку через skip_before_action  https://guides.rubyonrails.org/action_controller_overview.html#filters

2022-10-22 19:36 UTC, skyvlados commented on app/controllers/application_controller.rb
> +  before_action :check_session,
понял, спасибо, поправил)

2022-10-24 16:21 UTC, eugeneyak approved these changes

2022-10-24 19:31 UTC, merged